fix

diff --git a/config/testdata/az b/config/testdata/az
--- a/config/testdata/az
+++ b/config/testdata/az
@@ -31,7 +31,7 @@ fi
 if [ -n "$FAIL_IF_TENANT_ID_SET" ]; then
     for arg in "$@"; do
         if [[ "$arg" == "--tenant" ]]; then
-            echo "ERROR: Tenant shouldn't be specified for managed identity account"
+            echo 1>&2 "ERROR: Tenant shouldn't be specified for managed identity account"
             exit 1
         fi
     done
