work

diff --git a/config/testdata/az b/config/testdata/az
--- a/config/testdata/az
+++ b/config/testdata/az
@@ -27,6 +27,16 @@ if [ -n "$COUNT" ]; then
     echo -n x >> "$COUNT"
 fi
 
+# If FAIL_IF_TENANT_ID_SET is set & --tenant-id is passed, fail.
+if [ -n "$FAIL_IF_TENANT_ID_SET" ]; then
+    for arg in "$@"; do
+        if [[ "$arg" == "--tenant-id" ]]; then
+            echo "ERROR: Tenant shouldn't be specified for managed identity account"
+            exit 1
+        fi
+    done
+fi
+
 # Macos
 EXP="$(/bin/date -v+${EXPIRE:=10S} +'%F %T' 2>/dev/null)"
 if [ -z "${EXP}" ]; then
